# Generated by Django 2.2.4 on 2019-12-05 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='gradeentry',
            options={'verbose_name_plural': 'grade entries'},
        ),
        migrations.AlterField(
            model_name='category',
            name='max_points',
            field=models.FloatField(blank=True, null=True, verbose_name='Max Points'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_gen_ed',
            field=models.BooleanField(default=False, help_text='Whether the course is a general education requirement', verbose_name='Gen Ed'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='grading_strategy',
            field=models.CharField(blank=True, choices=[('point_based', 'Point Based'), ('weight_based', 'Weight Based')], default='weight_based', max_length=20, verbose_name='Grading Strategy'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='max_points',
            field=models.FloatField(blank=True, null=True, verbose_name='Maximum number of points attainable'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='course_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='concentration',
            field=models.ForeignKey(blank=True, help_text='Concentration the requirement is for (only if root requirement)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='grades.Concentration', verbose_name='Concentration'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='course_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of directly related courses that must be completed to fulfill the requirement', null=True, verbose_name='Course Count'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='is_required',
            field=models.BooleanField(blank=True, default=True, help_text='Set to false when requirement is one of many sub-requirements which do not all need to be completed', verbose_name='Required'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='sub_requirement_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of sub-requirements which must be completed to fulfill the requirement', null=True, verbose_name='Sub Requirement Count'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='sub_requirement_course_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of courses in directly related sub-requirements that must be completed to fulfill the requirement (including courses in sub-requirements that must be fulfilled)', null=True, verbose_name='Sub Requirement Course Count'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='super_requirement',
            field=models.ForeignKey(blank=True, help_text='Parent requirement which this requirement is a sub-requirement of (if sub-requirement)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_requirements', to='grades.Requirement', verbose_name='Parent Requirement'),
        ),
        migrations.AlterField(
            model_name='user',
            name='colleges',
            field=models.ManyToManyField(blank=True, related_name='students', to='grades.College'),
        ),
        migrations.AlterField(
            model_name='user',
            name='concentrations',
            field=models.ManyToManyField(blank=True, related_name='students', to='grades.Concentration'),
        ),
        migrations.AlterField(
            model_name='user',
            name='majors',
            field=models.ManyToManyField(blank=True, related_name='students', to='grades.Major'),
        ),
        migrations.AlterField(
            model_name='user',
            name='semesters',
            field=models.ManyToManyField(blank=True, related_name='students', to='grades.Semester'),
        ),
    ]
