sudo: false
language: generic
matrix:
  include:
    - os: linux
cache:
  directories:
    - "/tmp/texlive"
    - "$HOME/.texlive"
before_install:
  - travis_wait 45 bash ./utils/travis_latex_setup.sh
  - export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
script:
  - apt-get update
  - apt-get install pandoc
  - /bin/bash ./utils/build_docs.sh
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file:
      - /tmp/artifacts/docs/*
    skip_cleanup: true
    # on:
    #   repo: KYDronePilot/CSC-440-Team-Project
    #   tags: true
