sudo: false
language: generic
matrix:
  include:
    - os: linux
      services:
        - docker
      cache:
        directories:
          - "/tmp/texlive"
          - "$HOME/.texlive"
      before_install:
        - travis_wait 45 bash ./utils/travis_latex_setup.sh
        - export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
        - docker pull kydronepilot19/draw.io-builder
      script:
        - ./utils/install_travis_requirements.sh
        - ./utils/build_docs.sh
      deploy:
        - provider: releases
          api_key: $GITHUB_TOKEN
          file_glob: true
          file:
            - /tmp/artifacts/docs/*
          skip_cleanup: true
          on:
            repo: KYDronePilot/CSC-440-Team-Project
            tags: true
    - language: python
      python: '3.7'
      cache: pip
      before_script:
        - cd src/backend/csc_440_project_backend
        - python -m pip install -r requirements.txt
        - python manage.py makemigrations
      script:
        - python manage.py test
