sudo: false
language: generic
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=$coveralls_repo_token
matrix:
  include:
    - dist: bionic
      addons:
        apt:
          packages:
            - coreutils
      services:
        - docker
      cache:
        directories:
          - "/tmp/texlive"
          - "$HOME/.texlive"
      before_install:
        - travis_wait 45 bash ./utils/travis_latex_setup.sh
        - export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
        - docker pull kydronepilot19/draw.io-builder
      script:
        - ./utils/install_travis_requirements.sh
        - ./utils/build_docs.sh
      deploy:
        - provider: releases
          api_key: $GITHUB_TOKEN
          file_glob: true
          file:
            - /tmp/artifacts/docs/*
          skip_cleanup: true
          on:
            repo: KYDronePilot/CSC-440-Team-Project
            tags: true
    - language: python
      python: '3.7'
      cache: pip
      before_script:
        - cd src/backend/csc_440_project_backend
        - python -m pip install -r requirements.txt
        - python manage.py makemigrations
      script:
        - coverage run --source='.' manage.py test
      after_success:
        - COVERALLS_REPO_TOKEN=$coveralls_repo_token coveralls
    - name: 'Build/Distribute Frontend Container'
      language: node_js
      node_js: 'stable'
      cache:
        directories:
          - src/frontend/csc-440-project-frontend/node_modules
      before_script:
        - cd src/frontend/csc-440-project-frontend
        - yarn
      script:
        - yarn run test --coverage
        - yarn build
      after_script:
        - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn run coveralls
