sudo: false
language: generic
matrix:
  include:
    - name: 'Build Docs'
      dist: bionic
      addons:
        apt:
          packages:
            - coreutils
      services:
        - docker
      cache:
        directories:
          - "/tmp/texlive"
          - "$HOME/.texlive"
          - "/tmp/pandoc"
      before_install:
        - travis_wait 45 bash ./utils/travis_latex_setup.sh
        - export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
        - ./utils/install_pandoc.sh
        - docker pull kydronepilot19/draw.io-builder
      script:
        - ./utils/install_travis_requirements.sh
        - ./utils/build_docs.sh
      deploy:
        - provider: releases
          api_key: $GITHUB_TOKEN
          file_glob: true
          file:
            - /tmp/artifacts/docs/*
          skip_cleanup: true
          on:
            repo: KYDronePilot/CSC-440-Team-Project
            tags: true
    - name: 'Test, Build and Distribute Backend'
      language: python
      python: '3.7'
      services:
        - docker
      cache: pip
      env:
        - REPO=kydronepilot19/csc-440-project-backend
        - TAG=`if [ "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo $TRAVIS_BRANCH ; fi`
        - COMMIT=${TRAVIS_COMMIT::8}
      before_script:
        - cd src/backend/csc_440_project_backend
        
        # Install requirements
        - python -m pip install -r requirements.txt
        
        # Use template (base) dotenv file for building
        - cp base.env .env
      script:
        - python manage.py migrate
        - python manage.py test
        - python manage.py create_dummy_data
        - docker build -t $REPO:$COMMIT .
      after_success:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker tag $REPO:$COMMIT $REPO:$TAG
        - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
        - docker push $REPO
    - name: 'Build/Distribute Frontend Container'
      language: node_js
      node_js: 'stable'
      cache:
        directories:
          - src/frontend/csc-440-project-frontend/node_modules
      env:
        - REPO=kydronepilot19/csc-440-project-frontend
        - TAG=`if [ "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo $TRAVIS_BRANCH ; fi`
        - COMMIT=${TRAVIS_COMMIT::8}
      before_script:
        - cd src/frontend/csc-440-project-frontend
        - yarn
      script:
        - yarn build
        - docker build -t $REPO:$COMMIT .
      after_success:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker tag $REPO:$COMMIT $REPO:$TAG
        - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
        - docker push $REPO
