export const FETCH_SEMESTERS = 'FETCH_SEMESTERS';
export const NEW_SEMESTER = 'NEW_SEMESTER';

export const FETCH_COURSE_INSTANCES = 'FETCH_COURSE_INSTANCES';

export const FETCH_GRADE_ENTRIES = 'FETCH_GRADE_ENTRIES';
