export const FETCH_SEMESTERS = 'FETCH_SEMESTERS';
export const NEW_SEMESTER = 'NEW_SEMESTER';
export const SET_ACTIVE_SEMESTER = 'SET_ACTIVE_SEMESTER';
export const APPEND_SEMESTER = 'APPEND_SEMESTER';
export const DELETE_SEMESTER = 'DELETE_SEMESTER';


export const FETCH_GRADE_ENTRIES = 'FETCH_GRADE_ENTRIES';
export const ADD_GRADE_ENTRY = 'ADD_GRADE_ENTRY';
export const APPEND_GRADE_ENTRY = 'APPEND_GRADE_ENTRY';
export const REPLACE_GRADE_ENTRY = 'REPLACE_GRADE_ENTRY';
export const DELETE_GRADE_ENTRY = 'DELETE_GRADE_ENTRY';
export const SET_EDITED_GRADE_ENTRY = 'SET_EDITED_GRADE_ENTRY';

// Grade entry form
export const GRADE_ENTRY_FORM_ERROR = 'GRADE_ENTRY_FORM_ERROR';
export const GRADE_ENTRY_FORM_SUCCESS = 'GRADE_ENTRY_FORM_SUCCESS';
export const GRADE_ENTRY_FORM_OPEN = 'GRADE_ENTRY_FORM_OPEN';
export const GRADE_ENTRY_FORM_CLOSE = 'GRADE_ENTRY_FORM_CLOSE';
export const GRADE_ENTRY_FORM_SUBMITTED = 'GRADE_ENTRY_FORM_SUBMITTED';
export const GRADE_ENTRY_FORM_UPDATE_FIELD = 'GRADE_ENTRY_FORM_UPDATE_FIELD';
export const GRADE_ENTRY_FORM_UPDATE_STATE = 'GRADE_ENTRY_FORM_UPDATE_STATE';
export const GRADE_ENTRY_FORM_CLEAR = 'GRADE_ENTRY_FORM_CLEAR';
export const GRADE_ENTRY_FORM_LOAD_DATA = 'GRADE_ENTRY_FORM_LOAD_DATA';
export const GRADE_ENTRY_FORM_UPDATE_ENTRY = 'GRADE_ENTRY_FORM_UPDATE_ENTRY';
export const GRADE_ENTRY_SET_ACTIVE_CATEGORY_ID = 'GRADE_ENTRY_SET_ACTIVE_CATEGORY_ID';

export const GRADE_ENTRY_FORM_CREATE_MODE = 'GRADE_ENTRY_FORM_CREATE_MODE';
export const GRADE_ENTRY_FORM_EDIT_MODE = 'GRADE_ENTRY_FORM_EDIT_MODE';

export const GRADE_ENTRY_FORM_ENABLE_CREATE_MODE = 'GRADE_ENTRY_FORM_ENABLE_CREATE_MODE';
export const GRADE_ENTRY_FORM_ENABLE_EDIT_MODE = 'GRADE_ENTRY_FORM_ENABLE_EDIT_MODE';

// Course instance actions
export const FETCH_COURSE_INSTANCES = 'FETCH_COURSE_INSTANCES';
export const SET_ACTIVE_COURSE_INSTANCE = 'SET_ACTIVE_COURSE_INSTANCE';

// Special course instance constants
export const POINT_BASED = 'point_based';
export const WEIGHT_BASED = 'weight_based';

// Course actions
export const FETCH_COURSES = 'FETCH_COURSES';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

// Common actions
export const DATA_LOADED = 'DATA_LOADED';
export const DATA_NOT_LOADED = 'DATA_NOT_LOADED';

export const CATEGORY_FORM_CREATE_MODE = 'CATEGORY_FORM_CREATE_MODE';
export const CATEGORY_FORM_EDIT_MODE = 'CATEGORY_FORM_EDIT_MODE';
export const CATEGORY_FORM_ERROR = 'CATEGORY_FORM_ERROR';
export const CATEGORY_FORM_OPEN = 'CATEGORY_FORM_OPEN';
export const CATEGORY_FORM_CLOSE = 'CATEGORY_FORM_CLOSE';
export const CATEGORY_FORM_SUBMITTED = 'CATEGORY_FORM_SUBMITTED';
export const CATEGORY_FORM_UPDATE_FIELD = 'CATEGORY_FORM_UPDATE_FIELD';
export const CATEGORY_FORM_UPDATE_STATE = 'CATEGORY_FORM_UPDATE_STATE';
export const CATEGORY_FORM_CLEAR = 'CATEGORY_FORM_CLEAR';
export const CATEGORY_FORM_LOAD_DATA = 'CATEGORY_FORM_LOAD_DATA';
export const CATEGORY_FORM_CHANGE_MODE = 'CATEGORY_FORM_CHANGE_MODE';
export const CATEGORY_FORM_SET_EDIT_ID = 'CATEGORY_FORM_SET_EDIT_ID';
export const CATEGORY_FORM_SET_COURSE_INSTANCE_ID = 'CATEGORY_FORM_SET_COURSE_INSTANCE_ID';
export const APPEND_CATEGORY = 'APPEND_CATEGORY';
export const REPLACE_CATEGORY = 'REPLACE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

// Category score requirement actions
export const FETCH_CSRS = 'FETCH_CSRS';

// User specific actions
export const ADD_SEMESTER_TO_STUDENT = 'ADD_SEMESTER_TO_STUDENT';
export const REMOVE_SEMESTER_FROM_STUDENT = 'REMOVE_SEMESTER_FROM_STUDENT';
