export const FETCH_SEMESTERS = 'FETCH_SEMESTERS';
export const NEW_SEMESTER = 'NEW_SEMESTER';

export const FETCH_COURSE_INSTANCES = 'FETCH_COURSE_INSTANCES';

export const FETCH_GRADE_ENTRIES = 'FETCH_GRADE_ENTRIES';
export const ADD_GRADE_ENTRY = 'ADD_GRADE_ENTRY';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
