apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "progress-tracker-chart.fullname" . }}-gunicorn-configmap
  labels:
{{ include "progress-tracker-chart.labels" . | indent 4 }}
data:
{{ (.Files.Glob "files/gunicorn_config.py").AsConfig | indent 2 }}
