{{- if .Values.ingress.enabled -}}
{{- $fullName := include "progress-tracker-chart.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "progress-tracker-chart.labels" . | indent 4 }}
  {{- $values := .Values -}}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- if $values.certIssuer.create }}
    cert-manager.io/issuer: {{ $fullName }}-cert-issuer
  {{- end }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
      {{- range .Values.ingress.tls.hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
        {{- range .Values.ingress.paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
        {{- end }}
{{- end }}
