apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "progress-tracker-chart.fullname" . }}-nginx-configmap
  labels:
{{ include "progress-tracker-chart.labels" . | indent 4 }}
data:
{{ (.Files.Glob "files/nginx/*").AsConfig | indent 2 }}
